### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Review by straight-shoota — APPROVED** [review]

**Comment by straight-shoota** [comment]
For reference: this was originally proposed as part of https://github.com/crystal-lang/crystal/pull/11725

**Comment by straight-shoota** [comment]
@icyleaf Is it intended that the bot adds an approved label for *any* approval?

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Comment by icyleaf** [comment]
> @icyleaf Is it intended that the bot adds an approved label for _any_ approval?

I enable the trafico-bot but not configure. 🤣

**Pull request merged**
